[package]
name = "oelung"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
derive_builder = "0.20.2"
proc_macros = { package = "oelung_proc_macros", path = "proc_macros" }
smallvec = "1.15.1"
smol_str = "0.3.4"
squalid = { git = "https://github.com/helixbass/squalid", rev = "646f6bf" }
thiserror = "2.0.17"

[dev-dependencies]
anyhow = "1.0.100"
